### ISSUE TITLE
build errors introduced by a536270?

### ISSUE THREAD

**Issue by martinvonwittich** [miquels/webdav-server-rs#4]
I'm trying to build `webdav-server-rs`, but I'm getting the following errors:

```
martin.mein-iserv.de ~/webdav-server-rs # cargo build
   Compiling webdav-server v0.3.0 (/var/lib/iserv/remote-support/iserv-martin.von.wittich/webdav-server-rs)
error[E0433]: failed to resolve: use of undeclared crate or module `cache`
  --> src/auth.rs:28:17
   |
28 |                 cache::cached::set_pamcache_timeout(timeout);
   |                 ^^^^^ use of undeclared crate or module `cache`

error[E0433]: failed to resolve: use of undeclared type `IpAddr`
  --> src/auth.rs:78:17
   |
78 |                 IpAddr::V4(ip) => ip.to_string(),
   |                 ^^^^^^ use of undeclared type `IpAddr`

error[E0433]: failed to resolve: use of undeclared type `IpAddr`
  --> src/auth.rs:79:17
   |
79 |                 IpAddr::V6(ip) => ip.to_string(),
   |                 ^^^^^^ use of undeclared type `IpAddr`

error[E0433]: failed to resolve: use of undeclared crate or module `cache`
  --> src/auth.rs:87:15
   |
87 |         match cache::cached::pam_auth(pam_auth, service, user, pass, ip_ref).await {
   |               ^^^^^ use of undeclared crate or module `cache`

error[E0412]: cannot find type `PamAuth` in this scope
   --> src/cache.rs:142:19
    |
142 |         pam_auth: PamAuth,
    |                   ^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
98  |     use pam_sandboxed::PamAuth;
    |

error[E0412]: cannot find type `PamError` in this scope
   --> src/cache.rs:147:21
    |
147 |     ) -> Result<(), PamError>
    |                     ^^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
98  |     use pam_sandboxed::PamError;
    |

warning: unused imports: `PamAuth`, `PamError`
   --> src/cache.rs:151:29
    |
151 |         use pam_sandboxed::{PamAuth, PamError};
    |                             ^^^^^^^  ^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default

error: aborting due to 6 previous errors; 1 warning emitted

Some errors have detailed explanations: E0412, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `webdav-server`

To learn more, run the command again with --verbose.
```

Looks to me like these errors were introduced in a536270abd7a81df87aa18ea464b3875fec08d98; if I check out b20f569c6e4cd59d8d598bd90e8d5fc5db07e355, it works. I haphazardly patched the issues like this:

``` diff
martin.mein-iserv.de ~/webdav-server-rs (master) # git diff
diff --git a/src/auth.rs b/src/auth.rs
index fcfc876..429c1db 100644
--- a/src/auth.rs
+++ b/src/auth.rs
@@ -1,7 +1,8 @@
 use std::io;
-use std::net::SocketAddr;
+use std::net::{SocketAddr,IpAddr};
 use std::sync::Arc;
 
+use crate::cache;
 use crate::config::{AuthType, Config, Location};
 
 use headers::{authorization::Basic, Authorization, HeaderMapExt};
diff --git a/src/cache.rs b/src/cache.rs
index 1a72b91..ccb48d0 100644
--- a/src/cache.rs
+++ b/src/cache.rs
@@ -7,6 +7,9 @@ use std::option::Option;
 use std::sync::{Arc, Mutex};
 use std::time::{Duration, Instant};
 
+#[cfg(feature = "pam")]
+use pam_sandboxed::{PamAuth, PamError};
+
 #[allow(dead_code)]
 pub struct Cache<K, V> {
     intern: Mutex<Intern<K, V>>,
@@ -139,16 +142,15 @@ pub(crate) mod cached {
 
     #[cfg(feature = "pam")]
     pub async fn pam_auth<'a>(
-        pam_auth: PamAuth,
+        pam_auth: pam_sandboxed::PamAuth,
         service: &'a str,
         user: &'a str,
         pass: &'a str,
         remip: Option<&'a str>,
-    ) -> Result<(), PamError>
+    ) -> Result<(), pam_sandboxed::PamError>
     {
         use std::collections::hash_map::DefaultHasher;
         use std::hash::{Hash, Hasher};
-        use pam_sandboxed::{PamAuth, PamError};
 
         let mut s = DefaultHasher::new();
         service.hash(&mut s);
```

I'm still learning Rust, so take this with a grain of salt :)

**Comment by miquels** [comment]
Ah yes, I added support to build the server on OpenBSD, but I forgot to test a full build on Linux. Fixed in https://github.com/miquels/webdav-server-rs/commit/147aea25ced1ece6b66ea616232e7b32e9b29340 .
